### ISSUE TITLE
json module: RFC 7159 sec 8.1 enforcement breaks out-of-date API's

### ISSUE THREAD

**Issue by shenningsgard** [expressjs/body-parser#106]
By enforcing the use of UTF-8 in a breaking way, body-parser can no longer be used with third-party API's using non-compliant charsets (such as ISO-8859-1). Might it be advisable to create an options flag that allows reading/parsing of json with non-compliant charsets?

**Comment by dougwilson** [comment]
AFAIK there are already versions of this module that allow this; it is unlikely to be added here, though. You can also just use the text parser and then JSON.parse(req.body).

**Comment by dougwilson** [comment]
I'm also not sure how this could possibly ever affect "third party APIs", because this module is for requests to your server, which you define what you accept.

**Comment by shenningsgard** [comment]
The Cisco Mobility Services Engine has an http-based notification system that POSTs location updates to a configurable address. I'm using njs/express to process these requests (along with others). It's kind of an odd setup, but it's the way the Cisco MSE API does things for whatever reason.

**Comment by dougwilson** [comment]
Any reason you can't just use the text parser for your route?

**Comment by shenningsgard** [comment]
That's likely a good call, and what I'll end up doing (rather than commenting out the UTF-8 enforcement). I hadn't heard of the strict enforcement guidelines until I saw (your?) comment in the code. Is it uncommon to have so little control over server-to-server HTTP requests/responses?

**Comment by dougwilson** [comment]
Well, I would say it is uncommon to even find the JSON violations like this. They certainly can exist because there was a large gap between when people were using it and when it got officially defined. The funny part is usually when there is something sending a code page charset, they usually don't always even send the right encoding anyway.

**Comment by shenningsgard** [comment]
Considering the dreadful documentation provided by Cisco for this service, I can't say I'm surprised they chose to violate such a simple standard. Honestly, I'm surprised it works at all.

Thanks for the convo, Doug. I'll close this out.

**Comment by dougwilson** [comment]
No problem :) Usually this stuff is using in just out-facing APIs, where essentially you set the standard (just the majority use case); being strict let's people not think about what they are exposing (because that's just how short development time makes things go) and so we try to help curtail getting customers getting engrained into bad calls by simply preventing it :)

And yes, there are cases like yours where you may have no choice but to deviate, but in this case, it should be semi simple. I'm even going to post code when i get to a computer that I think is a good solution, to help out :)

**Comment by shenningsgard** [comment]
Excellent; thanks Doug! I'll send a knowingly-naive email to Cisco to let them know about the issue as well. Cheers!

**Comment by dougwilson** [comment]
```js
var bodyParser = require('body-parser')
var express = require('express')

var app = express()
var ciscoJsonParser = [bodyParser.text({ type: 'json' }), parseJsonTextBody]

app.post(ciscoJsonParser, function (req, res, next) {
  // route code
})

function parseJsonTextBody(req, res, next) {
  // you can wrap this in a try-catch if you want a 400 instead of 500 response code on failure
  req.body = req.body ? JSON.parse(req.body) : {}
  next()
}
```
