### ISSUE TITLE
req.body being generated without vital properties

### ISSUE THREAD

**Issue by shiboe** [expressjs/body-parser#109]
As of 1.13.0 req.body no longer has function .hasOwnProperty() and will now throw an error when attempting to use. Is it now being generated without Object.prototype?

Was not seeing this issue with previous versions up to v1.12.4

**Comment by dougwilson** [comment]
Looks like this is caused only when you use `urlencoded` and have `extended: true`. Looks like a change in the https://github.com/hapijs/qs library. If you are not using the `extended` functionality, you can always set it to `extended: false`, otherwise we really only have the following options:

1. Downgrade `qs` to an insecure version (not really an option)
2. Convince the `qs` folks to keep the `prototype` just like `JSON.parse` does.
3. Get someone reputable to create a new library we can use instead of `qs`.

**Comment by dougwilson** [comment]
(P.S. @shiboe , your code would have exploded anyway if a user send the body `hasOwnProperty=foo&a=b`, as `req.body.hasOwnProperty` would be `foo` and not a function, so you may want to change your code, in the end, if you care about not blowing up).

**Comment by shiboe** [comment]
Thanks for the quick response!

Updated to using: Object.prototype.hasOwnProperty.call which should solve both issues.

**Comment by dougwilson** [comment]
So I'm probably just going to downgrade `qs` for now and live with it, because I feel like this is just too surprising of a change to force users to live with. Thanks for bring it to my attention!

**Comment by dougwilson** [comment]
Published as 1.13.1
