### ISSUE TITLE
json request body parse

### ISSUE THREAD

**Issue by guowei1651** [expressjs/body-parser#118]
"name": "body-parser",  "version": "1.13.3",

my json request {user:'guow'}, but express request.body is { '{user:\'guow\'}': '' }

**Comment by dougwilson** [comment]
Hi! What you are showing means that you are accidentally sending your JSON as `application/x-www-form-urlencoded` to your server instead of JSON.

Your request is likely looking like the following:

```
Content-Type: application/x-www-form-urlencoded

{user:'guow'}
```

But JSON needs to look like the following:
```
Content-Type: application/json

{"user":"guow"}
```

If you like, please feel free to post your client-side code that is making the request and we can help you out :)
