### ISSUE TITLE
Getting EMFILE under high load

### ISSUE THREAD

**Issue by JustinDrake** [expressjs/body-parser#126]
I am stress testing my NodeJS server under very high load. Surprisingly, the weakest link seems to be `body-parser`. Every once in a while I get these errors:

```
UnsupportedMediaTypeError: unsupported charset "UTF-8"
    at /Users/justin/Desktop/Duo-Money/servers/node_modules/body-parser/lib/read.js:75:15
    at done (/Users/justin/Desktop/Duo-Money/servers/node_modules/body-parser/node_modules/raw-body/index.js:239:14)
    at /Users/justin/Desktop/Duo-Money/servers/node_modules/body-parser/node_modules/raw-body/index.js:217:7
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

**Comment by dougwilson** [comment]
Interesting. That specific error is coming from the `iconv-lite` module, as that error, based on the stack trace you provided, is coming from down deep at https://github.com/stream-utils/raw-body/blob/2.1.3/index.js#L36-L42 , where we are trying to do a `iconv.getDecoder('utf-8')` and the `iconv-lite` module is throwing some kind of error. Can you dig into your `node_modules` directory and add a log of what that thrown error is?

**Comment by dougwilson** [comment]
It's possible that the Node.js `require()` statement at https://github.com/ashtuchkin/iconv-lite/blob/v0.4.11/lib/index.js#L61 is failing under the load.

**Comment by JustinDrake** [comment]
Sometimes I get the following error:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: accept EMFILE
    at exports._errnoException (util.js:746:11)
    at TCP.onconnection (net.js:1308:24)
```

so your `require()` hypothesis sounds plausible. What exactly do you want to log?

**Comment by dougwilson** [comment]
> What exactly do you want to log?

I'll be releasing a new version of `raw-body` soon that won't swallow all errors into an invalid encoding error (such that weird errors like this will actually bubble up). For now, you'll have to get around in your `node_modules` folder and find https://github.com/stream-utils/raw-body/blob/2.1.3/index.js#L36-L42 and then what you'll wan to do is add a `console.error(e.stack)` in the catch block and see what it is.

**Comment by JustinDrake** [comment]
You nailed it, well done!

Below is the error object, and the stack trace.

```
{ [Error: ENFILE: file table overflow, open '/Users/justin/Desktop/Duo-Money/servers/node_modules/body-parser/node_modules/iconv-lite/encodings/index.js']
  errno: -23,
  code: 'ENFILE',
  syscall: 'open',
  path: '/Users/justin/Desktop/Duo-Money/servers/node_modules/body-parser/node_modules/iconv-lite/encodings/index.js' }
Error: ENFILE: file table overflow, open '/Users/justin/Desktop/Duo-Money/servers/node_modules/body-parser/node_modules/iconv-lite/encodings/index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.Module._extensions..js (module.js:451:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.getCodec (/Users/justin/Desktop/Duo-Money/servers/node_modules/body-parser/node_modules/iconv-lite/lib/index.js:61:27)
    at Object.getDecoder (/Users/justin/Desktop/Duo-Money/servers/node_modules/body-parser/node_modules/iconv-lite/lib/index.js:118:23)
```

**Comment by JustinDrake** [comment]
@dougwilson: What's the best way to prevent this error from polluting my console?

**Comment by dougwilson** [comment]
Hi @JustinDrake , sorry for the delayed reply. I'm not 100% sure what the question is; you can always prevent it from polluting your console from simply not printing it to the console where ever the print is occurring.

But as for the actual root cause of your error, it is very likely that your fd limit on the process you are loading testing is just way too low. Typically the limit is not very high, and if you happen to be running the server of Mac OS X, then it's really, really low.

There are two solutions you can try to fix the root cause for an error like this in your application:

1. Increase the file descriptor limit for your process, especially important if that process is running on Mac OS X. You should have this limit set to at least the number of parallel requests you are expecting your application to handle.
2. Patch Node.js with a module like `graceful-fs` (https://github.com/isaacs/node-graceful-fs#global-patching), which will modify code Node.js to actually handle `EMFILE` errors in your application, rather than making them fatal.

**Comment by dougwilson** [comment]
And now, as of commit 0dba9b7d7055174fb82fbcc630e1288bb9e902e3, this error will come through as a 500 response with the original stack instead of being hidden behind a 415.

**Comment by mikemaccana** [comment]
Just wanted to say thanks @dougwilson, I was getting the **unsupported charset "UTF-8" ** message (masking a different bug) and upgrading to 2.1.4 fixed it.
