### ISSUE TITLE
why is the parser limit defaulted to 100kb?

### ISSUE THREAD

**Issue by kangman** [expressjs/body-parser#129]
this limit seems very small to me.  I know you can just simply state a new amount but ran into some size 413 issues when sending data to loggly.

**Comment by dougwilson** [comment]
Basically because it's a safe default. It's much larger than most people ever need, but not too much. It actually meant that a really bad Node.js security issue that could bring down sites was side-stepped by this module having a sane default.

https://nodejs.org/en/blog/vulnerability/v8-memory-corruption-stack-overflow/
