### ISSUE TITLE
Bodypasser bug

### ISSUE THREAD

**Issue by bfwg** [expressjs/body-parser#130]
I try to use fetch in react native and  I got this ` '{"name":"Hubot","login":"hubot"}': '' }` instead of `{"name":"Hubot","login":"hubot"}'`

`fetch('http://127.0.0.1:3000/login', {
      method: 'post',
      body: JSON.stringify({
        name: 'Hubot',
        login: 'hubot',
      })
    })`

`app.post('/login', function (req, res) {
  console.log(req.body);
  res.send(req.body);
});`
app.use(bodyParser.urlencoded({ extended: true }));

**Comment by dougwilson** [comment]
Hi @bfwg , I assume you closed this issue because you figured out your issue, but to elaborate, the reason for this is because you are sending a JSON body but with the incorrect Content-Type header of `application/x-www-form-urlencoded`. The Content-Type should be `application/json` for JSON bodies.

**Comment by bfwg** [comment]
Hi @dougwilson, yes I find out that was the issue. Thank you very much!
