### ISSUE TITLE
trouble in npm install body-parser

### ISSUE THREAD

**Issue by surbhi92k** [expressjs/body-parser#135]
I'm working on a corporate network and it has blocked github, so npm doesn't work for me. As I'm new, please help me with what I could do here? [manually adding which files will help me out? Like adding only index.js would work or I need to add everything?]

**Comment by dougwilson** [comment]
Hm, that is a hard one to answer, because there are likely a lot of things involved.

If the reason you cannot use `npm` is because you have to setup some kind of proxy configuration for a corporate proxy, I'm sure the fine people of npm can help you out at https://github.com/npm/npm/issues

Otherwise, probably the simplest solution here is to go to a computer that can use `npm`, and run the following commands:
```
$ mkdir body-parser-temp
$ cd body-parser-temp
$ npm i body-parser
$ tar -zcf node_modules.tar.gz node_modules
```
Now take that resulting `node_modules.tar.gz` file and transfer it to the machine that you needed to run `npm` on in the first place and run the following:
```
$ cd /to/directory/you/would/npm_install
$ tar -zxf /path/to/node_modules.tar.gz
```
And then you should have the `body-parser` module and all it's dependencies installed :)

**Comment by surbhi92k** [comment]
Hey! Thanks :)
But I tried installing by setting up proxy and it worked. FYI: http://jjasonclark.com/how-to-setup-node-behind-web-proxy/

**Comment by dougwilson** [comment]
Neat!
