### ISSUE TITLE
Verify rawbody just for one path

### ISSUE THREAD

**Issue by aristidesfl** [expressjs/body-parser#152]
I'm using the json parser in all my paths with `app.use(bodyParser.json())`
Only for one of the paths I need to verify the raw body of the request with [coinbase.verifyCallback](https://github.com/coinbase/coinbase-node/blob/461acc93714e194659354abb1a4b5fdc7b06cd46/lib/Client.js#L247-L251)

I could use the verify function to get the raw body and then verify only on the path, but I don't want for all the paths to get the rawbody duplicated anyway. `app.use(bodyParser.json({verify:function(req,res,buf){req.rawBody=buf}}))`

Is there a way to use the verify function only in one of the paths? Do I have to specify the parser individually for every route? Is there a parser which doesn't process the body so it could be used additionally to the jsonParser in a specific route?

**Comment by dougwilson** [comment]
Hi! The absolute recommended way is to setup your parsing on all the routes that need them.

If you want this behavior for a global parser instead, then (assuming you are using Express), just add a specific-route parser above the general parser. For example:

```js
app.post('/some/special/route', bodyParser.json({verify:function(req,res,buf){req.rawBody=buf}}))
app.use(bodyParser.json())
```

**Comment by aristidesfl** [comment]
Won't bodyParser.json() be called twice for /some/special/route in that scenario?

**Comment by dougwilson** [comment]
Yes, but the second call will just bail if the first call parsed it.

**Comment by aristidesfl** [comment]
Ah, cool.

Would this be the same thing?
```
app.use('/some/special/route', bodyParser.json({verify:function(req,res,buf){req.rawBody=buf}}))
app.use(bodyParser.json())
```

**Comment by dougwilson** [comment]
It depends on your case-case specifically, which wasn't apparent in the original post. `app.use` has different path matching semantics than does `app.post`. For example, `app.use('/some/special/route', ...)` will match `GET /some/special/route/foo/bar/baz`, if that is intentional. If you want to simply match all methods for a given exact path, `app.all` does this.

**Comment by aristidesfl** [comment]
I thought there was a bigger difference between `app.all()` and `app.use()`. So its just the match semantics, right?

**Comment by dougwilson** [comment]
Correct. `app.all` will match just like the verb do, where the path is exact. `app.use` will do prefix matching instead of exact path matching. Both match all verbs, though.

**Comment by aristidesfl** [comment]
Thanks for the help

**Comment by aristidesfl** [comment]
Which kind of error must be thrown in order to stop the parser?

**Comment by dougwilson** [comment]
Any type of error.

**Comment by aristidesfl** [comment]
Isn't there a way to stop gracefully without creating an error?

**Comment by dougwilson** [comment]
Maybe. Can you elaborate more on what you mean by that?

**Comment by aristidesfl** [comment]
I mean, I don't want to throw an error for a condition I know it might happen and I control, I just want to respond to the request and log the event. Otherwise I will get stack traces like an exception occurred etc.

**Comment by dougwilson** [comment]
Gotcha. Well, getting stack traces depends of course on what your global error handler is doing :) Express 4 default handler will always log stack traces, but that was supposed to change in Express 5 to only log stack traces by default on 500+ errors (throwing in `verify` results in a 403 error by default.

If you are looking to use body parser and the verify function in order to validate the correctness of a request on a specific route, ideally if you added the body parser to the route itself, you could just add the specific error handler to that route as well. If you are looking to do this with a global error handler instead, there are two different methods:

1. Wrap the specific `body-parser` and intercept the `err` argument to the `next` function you define.
2. Add an error handler to the same path directly after the specific `body-parser`, throw an error in `verify` that you can detect and detect them in your error handler (and `next(err)` any that you don't want to respond to.

**Comment by aristidesfl** [comment]
I'm not sure I get the difference between
> ideally if you added the body parser to the route itself, you could just add the specific error handler to that route as well.

and 

> 2 Add an error handler to the same path directly after the specific body-parser, throw an error in verify that you can detect and detect them in your error handler (and next(err) any that you don't want to respond to

Could you give a quick example of the first?

**Comment by dougwilson** [comment]
The first would result in the following:
```js
app.all('/some/special/path', wrapMiddleware(bodyParser.json({ verify: verifySignature }), function (err, next) {
  // check to see if err is invalid signature & respond
}))

function verifySignature(req, res, buf) {
  // validate buf & throw, maybe
}

function wrapMiddleware(fn, cb) {
  return function (req, res, next) {
    return fn(req, res, function (err) {
      cb(err, next)
    }
  }
}
```

The second would result in the following:
```js
app.all('/some/special/path', bodyParser.json({ verify: verifySignature }), function (err, req, res, next) {
  // check to see if err is invalid signature & respond
})

function verifySignature(req, res, buf) {
  // validate buf & throw, maybe
}
```

I'm sure there are other possibilities as well; these things are really starting to turn into a how to handle errors from specific middleware question that is more about Express, rather than this module. This module works with anything, not just Express. For example, the tests for this module mount this middleware on a plain Node.js HTTP server and do not use Express at all.

Perhaps there is a way Express routing can help make handling these errors easier.

**Comment by aristidesfl** [comment]
Thanks for the example. What if instead of having to throw an error, `bodyparser` used the result of verify?

**Comment by dougwilson** [comment]
> What if instead of having to throw an error, bodyparser used the result of verify to decide if it should continue or not.

Maybe we can consider that for the next major version of this module. Can you outline the pros and cons for this proposal?

**Comment by aristidesfl** [comment]
I thought more about this case and maybe there is no point in what I was asking. I guess you don't see any either?

Thanks for the help :+1:

**Comment by dougwilson** [comment]
Well, it depends on what your desired outcome is. Is it to just not see stack traces for 4xx errors, since they are lame? Hopefully Express 5 will default to that behavior, but until then, you could modify your custom global error handler to not log (if you have one), or you can override the built-in error handler in Express like so:
```js
var express = require('express')
var finalhandler = require('finalhandler') // this is what Express uses for error responding
var http = require('http')

// .. stuff

var app = express()

// .. more stuff

// instead of calling app.listen() ..
http.createServer(function (req, res) {
  // invoke the app with a custom error logger
  app(req, res, finalhandler({
    env: app.get('env'),
    onerror: logerror
  }))
})

function logerror(err, res, res) {
  // just log 5xx errors
  if (res.statusCode >= 500) console.error(err.stack || err.toString())
}
```

If the goal is something else, let me know, and I can see what I can think of as well. You never know what changes can come out of this kind of brainstorming :)

**Comment by aristidesfl** [comment]
Yeah, that was the intention. 
One could also add an extra handler middleware to prevent the default logger from receiving them, right?
```
app.use(function(err, req, res, next) {
  if (res.statusCode >= 500) next(err)
})
```

**Comment by aristidesfl** [comment]
And.. why the need to set both status and statusCode? 
https://github.com/expressjs/body-parser/blob/master/lib/read.js#L185-L186

**Comment by dougwilson** [comment]
>  One could also add an extra handler middleware to prevent the default logger from receiving them, right?

Well, the issue there, which is tricky, is that if that is the entire error handler middleware, than for all non-5xx requests, the response will just hang, unless you add some code in there to send a response :)

> And.. why the need to set both status and statusCode? 

So, it is just for a historical compatibility thing. At first, we just used `err.status` to signal the status code, but over time we realized from user feedback that `err.status` is just too generic :) So we decided to change it to `err.statusCode`, and so have both just for backwards-compatibility. I would say to prefer `err.statusCode`, though last I checked, there is still a lot out in the ecosystem still providing the old `err.status`.
