### ISSUE TITLE
PHP req.body content as a string in one key

### ISSUE THREAD

**Issue by Maradonna90** [expressjs/body-parser#154]
I have a php script that sends a POST request via curl to a node-server
```php
                                $data = array("name" => "Hagrid", "age" => "36");                                                                    
				$data_string = json_encode($data);                                                                                   
				$curl = curl_init();                                                                      
				curl_setopt($curl, $url, "POST");                                                                     
				curl_setopt($curl, CURLOPT_POSTFIELDS, $data_string);
				curl_setopt($curl, CURLOPT_URL, $url);                                                                  
				curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);                                                                      
				curl_setopt($curl, CURLOPT_HTTPHEADER, $head);
                                curl_exec ( $curl );
			        curl_close ( $curl );
```

When I use body-parser to get the JSON into nodejs i recieve `{ '{"name":"Hagrid","age":"36"}': '' }`, while I get `{"name":"Hagrid","age":"36"}` from json_encode.

**Comment by dougwilson** [comment]
Hi! The issue here is that your request has the header `Content-Type: application/x-www-url-encoded`. You just need to set the `Content-Type` header to `application/json` to get it parsed as JSON, rather than parsed as a url-encoded body. You didn't post it, so I can't tell, but make sure you have `Content-Type: application/json` in your `$head` array.
