### ISSUE TITLE
body-parser cause memory leak?

### ISSUE THREAD

**Issue by omega4github** [expressjs/body-parser#160]
Hello,I installed express by express-generator,it contain body-parser directly.As it need recieve large data,it cannot work without configure '{limit: '50mb'}' in the code.after I adding configure of limit, It works now,but the memory increases all the time,until process is killed by OS, express recieve request every 10 seconds,request data size is about 100KB,the handler code is very simple, just print a string.
when I remove body-parser's code, the memory does not increase at all, but can not get request data now.I tried several versions like 1.13.2、1.14.2、1.15.0,every version has the problem.
My English is poor, wish you can understand me,if you reply to me ,please send an email to 398914521@qq.com.

**Comment by dougwilson** [comment]
Hi @omega4github, the question is hard to answer, because there isn't a lot of information on your problem to go on. Perhaps if I describe how this module works, it will explain what you are seeing.

When you use the body parser, this module will  buffer up the entire body into your Node.js memory before continuing. This is why the default limit is so small. If you are increasing the limit, you need to be very careful, as if you get many parallel requests with large bodies, your memory is going to balloon, which seems to be what you are describing.

**Comment by omega4github** [comment]
but the memory don't reduce at all after I stop sending request. it seems that the memory can not be recycled.
later I will make a demo and send it to you.

**Comment by dougwilson** [comment]
Hi @omega4github, it depends on a lot of factors, because Node.js/v8 doesn't just give back memory it doesn't use, with the anticipation it may need to use it again. What memory dump tools have you used? Can you see what objects are actually stuck on your heap rather than looking at just RSS by the OS?

**Comment by dougwilson** [comment]
You may want to stop by our Gitter channel http://gitter.im/expressjs/express for some live help in debugging your issue as well.

**Comment by omega4github** [comment]
hello, can you give me your email address? I can't reply to you with email,because my email system report an address error,and I also can not upload my demo file to github.I have finished a demo,may be it is useful to check the reason of this problem.

**Comment by dougwilson** [comment]
Hi @omega4github, it is listed on my GitHub profile, in this project all over the place as well. I do not have a lot of bandwidth, so I would suggest you try the Gitter channel before emailing me, if you want to get an answer quickly.

**Comment by Santiago-vdk** [comment]
Hi i'm having the same issue, @omega4github could you solve it? Or is there any solution?
