### ISSUE TITLE
req.body defaults to `{}` ? for .text as well?

### ISSUE THREAD

**Issue by ponelat** [expressjs/body-parser#170]
So I wrote a simple proxy, and did a naive check on `req.body`, to see whether I should proxy it.
This turned out to be true all the time... even with...
```js
app.use(bodyParser.text({type: '*/*' }) // req.body should only be text right?
```

Now I'm using the internal... `if(req._body) // there is a body`
Is that safe? Is there something I'm missing?

Perhaps we should change the default body to '', for the text parser? ( https://github.com/expressjs/body-parser/blob/master/lib/types/text.js#L62 )
Thanks for the great project, by the way :smile:

**Comment by dougwilson** [comment]
Yes, it does, unfortunately. This is already fixed, though, in the 2.x branch as we prepare to release 2.0 with breaking changes like this. Can you test the current 2.x branch and let me know what you think of the fix? You can find the installation instructions in the "Release 2.0" pull request.

You can also find a previous discussion in this in #128 I believe.

**Comment by ponelat** [comment]
Thanks for the reply... I should have searched for the issue. But I'm just too lazy.
Looking at `2.0`, defaulting to `undefined` makes sense. That would break things, that depend on it being a string. But I think its preferred. Look forward to the release.

Closing in favour of https://github.com/expressjs/body-parser/issues/128

**Comment by dougwilson** [comment]
Yea, and in case it helps, the reason it details as undefined vs an empty string is otherwise you would not be able to tell the difference between a non-text body (or no body) and a zero-length text body. We figure having req.body default to undefined makes sense, since having no body would mean the body is undefined. It would also play nice when you have multiple types of body parsers running at once on the same route (undefined means you didn't have a body, regardless of which parser you were using).

The empty object behavior is a dumb carryover from when there were only JSON and urlencoded parsers, but when text and raw were added, that defaulting behavior broke down, haha.

**Comment by ponelat** [comment]
Yup... I'm in favour of  `req.body === undefined // default value`... FWIW.

@dougwilson could we re-open #128 ? So that others might find this issue... until 2.0 gets released?

**Comment by dougwilson** [comment]
@ponelat, why re-open the issue? The change has already been merged into the 2.0 branch. Simply keeping the issue open is not going to help.

**Comment by ponelat** [comment]
Sure, makes sense. My thought was for visibility, if the issue is closed - I imagined it to be fixed in the latest ( my mistake is assuming that the latest is in master, or npm ). But that's just an opinion :smile:
I'm not too bothered, now that *I* know its in 2.0

**Comment by dougwilson** [comment]
Hi @ponelat, it's always a tricky question, of course. I've tried all different ways and there is always someone who comes long and wants it done differently, so the policy as it is today is just how it is. Of course, it's made more complicated in that this issue was fixed before any issue was actually filed for it, making all future comments on it technically questions, with the answer being "we've already fixed it pending 2.x".

Even the `master` option is hard, because of course if this was on `master`, then the documentation on the main GitHub page would no longer match what is in npm, which creates a lot of confusion, as I find that many, many people just come to the GitHub page for documentation, without validating that the page actually corresponds to the version they are using.
