### ISSUE TITLE
Not able to set limit in body parser

### ISSUE THREAD

**Issue by UditKaul** [expressjs/body-parser#176]
I am trying to increase the limit of request entity allowed in body-parser. I tried this but was no good.
app.use(bodyParser());
 app.use(bodyParser({limit: '50mb'}));
 app.use(bodyParser.urlencoded({limit: '50mb'}));

The error message says "Error: request entity too large" and the status code is 413.

**Comment by Thanatos-L** [comment]
I have the same problem and I'm trying to add:

`app.use(bodyParser.raw({limit: "50mb"}));`

then get error: bodyParser.raw is not a function.

I use AFNetworking to upload a picture which no more than 1mb.

```
NSString *urlString = [baseUrlString stringByAppendingString:@"account/avatar"];
    
    NSDictionary *parameters = @{@"token": self.token};
    NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
    AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:configuration];
    
    NSMutableURLRequest *request = [[AFHTTPRequestSerializer serializer] requestWithMethod:@"POST" URLString:urlString parameters:parameters error:nil];
    //[request setValue:@"application/json" forHTTPHeaderField:@"Accept"];
    //[request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
    NSURLSessionUploadTask *uploadTask = [manager uploadTaskWithRequest:request fromFile:filePath progress:nil completionHandler:^(NSURLResponse *response, id responseObject, NSError *error) {
        if (error) {
            NSLog(@"Error: %@", error);
        } else {
            NSLog(@"Success: %@ %@", response, responseObject);
        }
    }];
    [uploadTask resume];
```

**Comment by dougwilson** [comment]
Hi @UditKaul, I cannot reproduce your issue, and there is almost no information to go on in your report. Can you please provide all the following?

1. The version of this module you are using.
2. The version of Node.js you are using.
3. A complete app (not just a snippet like you pasted above) that we can copy-and-paste and run. Please include as little other dependencies as possible, to reduce the surface area of the investigation.
4. Please provide the complete steps to reproduce the issue. This may be a cURL command, for example. Explain what happens when it is not working, and explain what you expect to happen.

@Thanatos-L your issue sounds different from the one above, in particular, your `bodyParser` variable is either not from this module, or it is a very old version of this module, before `raw` was added. Please consult the `README.md` file for the installed `body-parser` version you are using to determine what functionality is available.

**Comment by UditKaul** [comment]
@dougwilson  thank you for your concern,but i found a solution to my problem just by doing the following.

app.use(bodyParser({limit: '50mb'}));
app.use(bodyParser.urlencoded({limit: '50mb'}));
app.use(bodyParser());

**Comment by dougwilson** [comment]
Hi @UditKaul, oh, wow, I'm really sorry, but I actually copy-and-pasted your code incorrectly myself when I tried to test! So the reason why
```js
app.use(bodyParser());
app.use(bodyParser({limit: '50mb'}));
app.use(bodyParser.urlencoded({limit: '50mb'}));
```

does not work is because you are using it over and over. I was assuming that you were simply showing three different ways, not that you actually had all three of those in your code. You see, you are actually defining the same body parsing multiple times for no reason, and since `bodyParser()` byt itself will parse both url encoded and json bodies, it it always meet first, and the second two literally do nothing.

Now in your new example, the first `app.use(bodyParser({limit: '50mb'}));` does all the work while your other two statements are doing absolutely nothing, so you can simply remove them.

**Comment by riginoommen** [comment]
Try this way

app.use(bodyParser.json({limit:1024*1024*20, type:'application/json'}));

**Comment by keithmichelson** [comment]
@riginoommen This worked for me, but what number are you passing in? Is that in bytes?

**Comment by Dajust** [comment]
@keithmichelson 1million bytes === 1MB. I personally don't want to exceed 50Mb, so I use 50000000 bytes.

**Comment by omt66** [comment]
For me the following solved the similar issue:

app.use(bodyParser.json({ limit: "15MB", type:'application/json'}));

I think the "type:application/json" was missing as mentioned by @riginoommen

**Comment by riginoommen** [comment]
@omt66 Yes i may missed this but that fix works

**Comment by ShreyaMishra22** [comment]
app.use(bodyParser.urlencoded({limit: '500mb', extended: true}));
app.use(bodyParser()); 

This will definitely work in every aspect.
