### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by Timokasse** [expressjs/body-parser#179]
Hello,

Might not be a big issue, might not be an issue at all, but I noticed a very common problem with this documentation: **not enough context**.
For example:

- What is a **body** in this context?
- Why would you want to parse it?
- What is an URL encoded body?
- Explanations have to bring value ("body-parser is a middleware to parse a body", "urlencoded only parses URL encoded bodies", ....)

OK, no need to go into much details, but if each documentation requires many more questions to our G friend, it will be a long journey.

Please be sure that I do not want to sound harsh or bitter. Please simply allow us noobs to join in. Thanks,
Timok

**Comment by dougwilson** [comment]
Hey, it's no problem! I find it is always a really hard balance to understand how far down the rabbit hole to go, and how much we should expect the readers to understand prior to using this documentation.

I know all your questions are valid, but so is "what is a middleware" "what is express" "what is HTTP" "what is JavaScript" and so much more.

Im going to close this issue, not because it's not really valid, but it pretty much asks the impossible, to document so many things that are already specified  elsewhere and can quadruple the six of this document if not more.

I think a better approach here would be to make a pull request adding the documentation you feel useful, rather than asking for it to appear, if that makes sense. Or maybe we can setup a bounty program?

**Comment by Timokasse** [comment]
Hello Doug,

You are right! It's difficult to know the limit. 

But in this case 'body' is both a very generic word (I have learned recently the term 'weasel word' for this) and a key word to understand the whole point of this piece of software. So I think that an explanation would be very much appreciated.

Also, unlike 'middleware', 'express' and 'HTTP', from what I understand now, 'body' is not a complete term. What it refers to, really, is 'request body'.

Now the reason I opened an issue for this is that I felt that I would not be the best person to propose a solution here, since I hardly understand the concepts. And this is probably the same reason why any issue is created here. Of course people could propose solutions instead, if they knew how.

Finally, having said that, I will be happy to attempt to help and will soon submit a pull request.

Cheers,
Timok

**Comment by dougwilson** [comment]
Hi @Timokasse, I understand that is can be unclear. I think the reason people typically just call it "body" is because from the HTTP specifications, it is actually called "entity body" and no one wants to call it that, so just "body" is fine in most cases. If you are trying to differentiate between request/response, that additional qualifier can be prefixed, of course. I think that it wasn't obvious to people like myself that adding that would make this clearer, because having the knowledge can make it hard to understand how those without see the world. For example, thinking back on it, I never questioned the use of the word "body" when it is next to "parser" because there is only one body that one would want to parse in a server setting: the request body.

I know you may not feel like the best person right now, but on the contrary, you are actually the best person of all to make the suggestions to the improvements, because you very well understand what is unclear to someone in your situation, and though you may not be able to articulate it at first, once you understand the concept, you are in the very unique situation to provide a very valuable documentation change with the fresh knowledge of what would have helped you.
