### ISSUE TITLE
unable to parse data from chrome FormData

### ISSUE THREAD

**Issue by calidion** [expressjs/body-parser#184]
got
```
{ '------WebKitFormBoundaryooIjxXjbckIutEpY\r\nContent-Disposition: form-data; name': '"id"\r\n\r\nsdofdsfo\r\n------WebKitFormBoundaryooIjxXjbckIutEpY\r\nContent-Disposition: form-data; name="secret"\r\n\r\nsdfosfo\r\n------WebKitFormBoundaryooIjxXjbckIutEpY\r\nContent-Disposition: form-data; name="token"\r\n\r\nsdofsofdfd\r\n------WebKitFormBoundaryooIjxXjbckIutEpY--\r\n' }
```
should be
```
{
id : 'sdofdsfo',
secret: 'sdfosfo',
token: 'sdofsofdfd'
}
```

**Comment by calidion** [comment]
a problem caused by jquery

**Comment by dougwilson** [comment]
Hi @calidion, sorry you had trouble. The issue is not actually with jQuery, rather just with your newness to using the `FormData` object and what it actually does :) You can see a better explanation at https://github.com/expressjs/body-parser/issues/181#issuecomment-228779696

You may also find it useful to use the search issues feature on GitHub, as this exact issue is in the history and you may have been able to get an answer quickly :)
