### ISSUE TITLE
Using bodyParser type option with content-type header

### ISSUE THREAD

**Issue by getupandgo** [expressjs/body-parser#190]
I need to use bodyParser.raw parser only when req.headers.content-type is 'raw' (because app must handle many requests with different types). But when i define this header in postman and then trying to use bodyParser like this i'm getting an empty req.body: 
```
app.use(bodyParser.raw({
  type: 'raw',
  limit: config.proxy.bodyparserlimit
}))

app.use(bodyParser.json({
  limit: config.proxy.bodyparserlimit
}))

app.use(bodyParser.urlencoded({
  limit: config.proxy.bodyparserlimit,
  extended: true
}))
```

```
app.post('/', upload.any(), function (req, res) {
  var requestData = req.body

  requestData.contentType = req.headers['content-type']
}
```
Seems like bodyParser trying to find type field in req.body, but there is nothing there. So how can I use type option with Content-Type header?

**Comment by dougwilson** [comment]
I'm not sure what you are doing and how you can even get that error. Can you provide me with all the following?

1. Version of Node.js
2. Version of this module.
3. Complete code that I can use to reproduce the issue. I will simply copy and paste it into a file to run, so it needs to be complete.
4. The exact steps I need yo do to cause the issue.

**Comment by getupandgo** [comment]
Please, don't mind that error - that was my bad :sweat_smile: 
But i'm still getting empty req.body, though
1. node v5.11.1
2. bodyParser version: 1.14.2 / 2015-12-16
3. https://github.com/getupandgo/bodyParser-reproducing/blob/master/app.js
4. https://github.com/getupandgo/bodyParser-reproducing/blob/master/README.md

**Comment by dougwilson** [comment]
Hey @getupandgo, it's no problem :) As for your `type: 'raw'` issue, this is because `body-parser` will take what you gave as type and hands it to `type-is` module (see docs https://github.com/expressjs/body-parser#type). If you give it a simple string, it looks like what the MIME type is for that file extension. In this case, it tries to use whatever the file `.raw` is, which does not exist, and ends up never matching any requests at all.

If you really want to match the header `Content-Type: raw`, you should just use a function and do it manually. Example:
```js
app.use(bodyParser.raw({
  type: function (req) { return req.headers['content-type'] === 'raw' },
  limit: config.proxy.bodyparserlimit
}))
```

**Comment by getupandgo** [comment]
Yes, it worked!
Thanks!

**Comment by dougwilson** [comment]
Awesome, good to hear!
