### ISSUE TITLE
Raw Body Parser and Large Payloads

### ISSUE THREAD

**Issue by nmagerko** [expressjs/body-parser#191]
I'm writing an application that is intended to accept the raw content of small payloads (under 2MB) of a specific content type (let's say `application/pdf`). The body parser that I am using in my application looks something like this:

```
app.use(bodyParser.raw({ limit: '2mb', type: 'application/pdf' }));
```
From what I've seen, an HTTP 413 error will be thrown if the incoming content exceeds the provided limit, and the request body (`req.body`) will be an empty object if the type does not match the specified type.

However, I'm concerned about malicious users who try to send a stream of hundreds (or thousands) of megabytes of data. The application will be running on instances of ~2 GB each, so very large payloads could easily consume all working memory if the entire incoming buffer is read and stored in memory with each request.

Thus, I was wondering how the body parser handles raw payloads that violate the size limit and if there is anything I can do to prevent malicious users from consuming all of my application's working memory with a large payload. I am using the latest version of this package and NodeJS 4.4.x.

**Comment by dougwilson** [comment]
Hi @nmagerko, how exactly you need to protect yourself from such attacks is beyod the scope of this module, but I can answer some of the specific questions regarding this module:

When you give this module a `req` object, the code will check the value of `req.headers['content-length']`, and if defined, will instantly error if that value is above the configured limit without ever reading the body. If instead the request is done using chunked encoding (and thus this module does not know how big the body is up-font), the module will read from the `req` object stream, and as soon as the buffered content + a new chunk is above the configured limit, this module will call `.pause()` on the `req` stream and error out.

Of course, how well that protects you from those attacks really depends on exactly how your `req` object stream works. If, for example, it buffers up before giving the object to this module, this module cannot help you. If the steam internally buffers up while we read, then it's certainly possible that you need more memory than you would expect, since you would need to also hold whatever internally buffer the stream is using.

I hope this helps. I have not done too much testing around this, mainly because I am always running Node.js behind WAF & IDS appliances that provide these safeguards in the layer above. I highly recommend you perform your own testing to understand if this module actually meets your needs to be sure. If you have findings, suggested fixes, etc. please let me know!

If you find something that is potentially a DoS vector, please follow the Express.js security procedure at https://github.com/expressjs/express/blob/master/Security.md to report it, rather than replying here.

**Comment by nmagerko** [comment]
Thanks! That information about the content length header is very good to know and so is the info about how to place this module in my request object stream. 

I appreciate it!
