### ISSUE TITLE
catch body in middleware

### ISSUE THREAD

**Issue by fithwith** [expressjs/body-parser#212]
I'm trying to catch the body in a middle-ware for logging purpose but I'm always getting an empty object, here what I'm trying to do:

```js
app.use(function(req, res, next){
   console.log(req.body);
    next();
});

```

**Comment by dougwilson** [comment]
That should work just fine, but without context of where that middleware is located and how you're using this module it's hard to answer. Can you post the following?

1. The version of Node.js you are using.
2. The version of this module you are using.
3. The full application that middleware is in, namely so I can understand the context or run it myself if we need to debug it,
4. The request you are making to the server that you are expecting to populate the `req.body` property. Usually a cURL command is good since it contains all the information I would need to recreate the request for testing.

Thanks!

**Comment by fithwith** [comment]
1-node : 6.0.0
2-"body-parser": "^1.15.2"
3-impossible to provide you with the full app
4-just fill any form and submit it, there is nothing crazy there.

just to clarify the vision, in the route it self I'm receiving the body normally without any problems, the problem is to intercept the body before the route, I think its coming from the fact that the body is in json, in that case how can I catch it.
this is part of the code:

```
app.use(function(req, res, next){
    console.log({  body:req.body  }); //here the body is empty
    next();
});

app.post('/foobar',bodyParser.json(), function(req, res) {
console.log(req.body); //here its working fine, I'm receiving the body correctly
});

```

**Comment by dougwilson** [comment]
Ah, I see your issue now. You see, this middleware is what populates the `req.body` property. By this nature, if you try and access `req.body` before this middleware ever ran, you won't get the body, which is what you're trying to do. Your `app.use` is before the `bodyParser.json()`.

**Comment by fithwith** [comment]
is it possible to do the parsing in the middleware ? or somewhere else ?  I mean for sure there is a workaround.

**Comment by dougwilson** [comment]
Hi @fithwith you just need to have the `bodyParser.json()` above anywhere you are trying to access the values it produces. There are many, many ways to achieve this, and I would need to understand more about what you're trying to accomplish to be able to provide a solution that makes sense for your situation.

**Comment by fithwith** [comment]
as I said in the first email, its for logging purpose.

**Comment by dougwilson** [comment]
Are you just logging via `console.log`? Do you want the log to happen before your handler processes the data, after it processes the data, or don't care? Do you want the log to occur only for the handers that have the body parser or for every handler?

**Comment by fithwith** [comment]
-I'm writing the log in a file.
-I want it for all the handlers.
-I want it before handler process with the request.

if its possible to parse the body in a separate midduleware and then avoid using bodyParser.json() in the handler, this will be a good solution for me.
note that not all the handler are using json, some of them are using simple text.
it will be really nice if I can do something like

```
//use this middleware only for parsing.
app.use(function(req, res, next){
    // parsing the body here
    next();
});
app.use(function(req, res, next){
    console.log({  body:req.body  }); //catching the body already parsed here and save it in the file
    next();
});

app.post('/foobar',function(req, res) {
console.log(req.body); //receiving the request and process it
});
```

**Comment by fithwith** [comment]
I tried this and its working fine, the trick is that its working even if my body is not supposed to be in a  json format, can this create a problem for me?

```
app.use(bodyParser.json());
app.use(function(req, res, next){
    console.log({  body:req.body  });
    next();
});
app.post('/foo',function(req, res) {
 //should receive a json body
});
app.post('/bar',function(req, res) {
 //should receive a text body
});
```

**Comment by fithwith** [comment]
I took a look on the bodyparser source code and look like before parsing its checking if the mime type is conform with what you want to parse, if yes it proceed if not it skip, so I think putting multiple middle-ware  like i did is safe.
thank you for your support.

**Comment by dougwilson** [comment]
Hi @fithwith when you say you have one doing JSON and the other doing test, are you saying one is `bodyParser.json()` and the other is `bodyParser.text()`? So since each of these middlewares skip if they do not apply to the request (i.e. they skip if their set type is not the same type of the request) then you can stack them on each other. The only downside is that now `req.body` could be _either_ JSON or text content, instead of only ever `{}` or the content your route was expecting. This may or may not matter to your code.

If you are looking to log the `req.body` as a generic middleware for all handers, there are two ways to do this without changing the semantics from your original post:

The first is to just move the body parser middleware up above the middleware. Example:
```js
app.post('/foobar', bodyParser.json()); // parse here before logging

app.use(function(req, res, next){
    console.log({  body:req.body  }); // log it here
    next();
});

app.post('/foobar', function(req, res) {
  console.log(req.body); // hander here, after parsing and logging
});
```

The second is to decorate our middleware with your logging function, to reduce boilerplate:
```js
app.post('/foobar', parseJson(), function(req, res) {
  console.log(req.body); // hander here, after parsing and logging
});

function parseJson(opts) {
  var parser = bodyParser.json(opts);
  return function (req, res, next) {
    return parser(req, res, function (err) { // parse
      if (err) return next(err);
      console.log({ body: req.body }); // log it here
      return next();
    });
  };
}
```

I hope this helps!
