### ISSUE TITLE
async verify

### ISSUE THREAD

**Issue by donpark** [expressjs/body-parser#218]
I've added [async verify support in my fork](https://github.com/donpark/body-parser/blob/async-verify/lib/read.js) because my app's verification process requires pulling information from async data sources.

To  support async verify, I check the number of arguments verify function accepts. If it's 4 then call it synchronously. If not, call asynchronously with callback as last argument.

Let me know when and if you'd like a PR.

**Comment by dougwilson** [comment]
Hi @donpark right now `verify` is sync only API, yes. It was added strictly to just be compatible with the body parser that was a part of connect / express 3. Ideally, we wanted to remove it completely, so I would love to better understand exactly what you are using it for first.

In addition, we have found that requiring a specific number of arguments on a function is just not a good API and is too hard to use when combined with `.bind()`, linters, etc. We would definitely need it to not use an arguments check.

**Comment by donpark** [comment]
@dougwilson I agree on argument count not being a robust solution. I made the patch just to workaround a short term issue and filed this issue as a curtesy of sort. You're welcome to ignore it.

Re why async verify is needed, my API uses JWT token with hash of POST body as part of the JWT claims. For server-side verification, I need to recalculate the hash of the body which means I need access to the raw body data.

Ideal solution would be to have body-parser pass the raw data somehow (request maybe) to subsequent middleware but I failed to find it so went with verify callback which does provide what I need. I could have just stashed the body Buffer in the request to pickup again in another middleware but that seemed brittle too.

**Comment by dougwilson** [comment]
Yea, makes sense, and that is the purpose of the verify function. I guess I still don't understand also exactly the use-case for having it async vs sync. You said you needed to pull information from async data sources. Can you expand on that, namely why it would need to be done within the verify function directly vs outside? Just seeking to understand the problem set, because sometimes understanding the problem being solved can result in an even better API rather than just tacking onto an existing on.

**Comment by donpark** [comment]
@dougwilson because I was in too much haste to draw a straight line from end-to-end instead of taking the time to just save ref to raw body Buffer in request from within verify then use it from another middleware that validates JWT token asynchronously. shameful but common

All this would not have been necessary if body-parser exposed raw body. Ball is now in your side of the court, doug. ;-p

**Comment by dougwilson** [comment]
I mean, I still don't understand your use-case. And we expose the raw body if you use the raw parser, of course. The other parsers are really for the convenience when you don't need the raw body.

**Comment by donpark** [comment]
Raw payload is needed for JWT token validation. Payload is JSON so bodyParser.json() is also needed. Body processing code is unaware of JWT token validation except for extra `auth` field in the request that provides verified identify information filled in by JWT token validation code.

**Comment by dougwilson** [comment]
Yea, but what is the async operation you are doing is what I'm trying to figure out? Like I said, the JSON parser is really just for the convenience for when you don't need the raw body, which covers 99% of the cases. The other 1% is why the raw parser even exists, and that's the better implementation anyway.

I'm trying to learn more about exactly what you're doing to make sure that actually adding this API is the correct course to take with the mode, rather than going to a hole support hacks on hacks is all. The verify as it is today is a hack, and I'm trying to determine why exactly it needs to be expanded when it's already on the chopping block.

Understanding exactly what your doing, ideally with code examples, will help us a lot.

**Comment by donpark** [comment]
OK. I'll try to clarify what I'm recommend.

1. I'm not advocating async verify. As you said, it's a hack. Async verify is also a hack.
2. I am advocating that body parser expose raw body in addition to processed body. Perhaps `request.rawBody`, for use-cases in which raw body is also needed. In my case, it's being used to calculate hash to protect against tempering.

**Comment by dougwilson** [comment]
The problem with that is now every request will take up 2x the RAM when 99% of the use cases will never need it.

**Comment by dougwilson** [comment]
Use the raw body parser.

**Comment by donpark** [comment]
That was a rather surprising abrupt end to this discussion but I'll go with third option: 1) use synchronous `verify` to calculate hash, 2) store the hash in request to be used by subsequent middleware. This approach does not keep raw body Buffer around, just its hash. Not a general solution but fits my needs without resorting to async verify.

Thx for the discussion.
