### ISSUE TITLE
How to handle bodyParser.json() errors?

### ISSUE THREAD

**Issue by AndreMaz** [expressjs/body-parser#244]
How to properly handle the errors that may result from bodyParser.json()?

I've created a simple app and some use cases to demonstrate what I'm talking about
**App**
```javascript
const express = require('express')
const bodyParser = require('body-parser')
const app = express()

app.use(bodyParser.json())

app.use((err, req, res, next) => {
  if (err) {
    console.log('Invalid Request data')
    res.send('Invalid Request data')
  } else {
    next()
  }
})

app.post('/', (req, res) => {
  res.send(req.body)   // send back the posted data
})

app.get('/', (req, res) => {
  res.send('Hello World!') // say Hello
})

app.listen(3000, () => {
  console.log('Example app listening on port 3000!')
})

```
**Use Case 1 - Request done properly** -> Works as expected
Req: `curl -XPOST -H "Content-type: application/json" -d '{"message": "test message"}' 'http://localhost:3000/'`
Res: `{"message":"test message"}`

**Use Case 2 - Invalid JSON** -> Works as expected
Req: `curl -XPOST -H "Content-type: application/json" -d '{"message": "test message}' 'http://localhost:3000/'`
Res: `{
  "body": "{\r\n\t\"message\": \"test message\r\n}",
  "status": 400,
  "statusCode": 400
}`

**Use Case 3 - Wrong Content Type** -> Returns empty body as response
Req: `curl -XPOST -H "Content-type: application/not-json" -d '{"message": "test message}' 'http://localhost:3000/'`
Res: `{ }`

I was expecting that in Use Case 3 some error would be thrown because `Content-type: application/not-json` should not be accepted.

**Use Case 4 - Wrong Content-Length** -> Empty reply from server
Req: `curl -XPOST -H 'Content-Length: 1' -H "Content-type: application/json" -d '{"message": "test message"}' 'http://localhost:3000/''`
Res: `curl: (52) Empty reply from server`

The Use Case 4 prints the `Invalid Request data` on the console but does not sends it to the client.

So the question is: how to properly handle the errors that may result from bodyParser?

**Comment by dougwilson** [comment]
Hi @AndreMaz here are the answers for the two cases that are not working as you expected:

Case 3 is correct - each middleware as a type to filter the request on. By default, the `.json()` parser only even looks at the requests that have `Content-Type: application/json` header, and all other requests are simply ignored. Thus requests without that content-type header are not in error, they are simply unhandled by the middleware. This is to enable stacking multiple middleware together / all the users who slap a `.json()` middleware at the top of their app (otherwise every single request without a json body would get rejected -- even GETs).

Case 4 is sadly the state of Node.js. You see, in the situation you provided, it is the low-level Node.js HTTP implementation that is closing the socket on you, because it is getting malformed data on the incoming socket. The Node.js HTTP server implementation is expecting a new request after the first, but the data it gets for the next request in your example is `"message": "test message"}`, which is not what it was expecting (it expected to see `\r\n`, then the HTTP method, space, the URL, space, `HTTP/` version, etc.) so it just closes the socket.

If you don't want Node.js to close the connection, you need to add the `clientError` event listener on your HTTP server instance (https://nodejs.org/dist/latest-v7.x/docs/api/http.html#http_event_clienterror) to do something different. Of course, that still won't allow you to directly tell that the request had a `Content-Length` that was too short. Since the `Content-Length` is actually what divides the requests from the RFC 7230, it's not possible to distinguish the content length mismatch using the Node.js HTTP API--but if you have some insight on how to achieve that, definitely put together a pull request :) !

**Comment by Al2Klimov** [comment]
@AndreMaz https://stackoverflow.com/questions/15819337/catch-express-bodyparser-error/48138247#48138247
