### ISSUE TITLE
How to turn off global middleware for a specific route?

### ISSUE THREAD

**Issue by timaschew** [expressjs/body-parser#245]
If I use 
```
app.use(bodyParser.json({limit: '900kb'}))
```

Can I turn this type of parser off for a specific route?
I know that I can include the middleware in all express routes before the `(req, res) =>` but I don't want to list them everywhere except for one specific route.

This specific route comes from a mailjet webhook, it has the `application/json` content type, but the payload contains large numbers (like 180145802706626361), which cannot be parsed with the default json parser, I need to use https://github.com/sidorares/json-bigint for it.

**Comment by dougwilson** [comment]
Hi @timaschew ! So this module is just a standard Express.js middleware: it will process whatever goes through it. This of course means if you don't want a particular request to be processed, you need to prevent the request from invoking the middleware, just like you would do if any other middleware you wanted to do this with.

This middleware (like virtually every other middleware out there), does not have a way to exclude it from certain requests, since the method in which users would desire to exclude can be anything--url, header, query string, loaded user, and more. Instead middleware places the logic of pathing on you: either (a) explicitly include it (which means placing on the routes, as recommended in our documentation) or (b) wrap the middleware with your own exclusion logic:
```js
var parseJSON = bodyParser.json({ limit: '900kb' })
app.use((req, res, next) => shouldParseRequest(req) ? parseJSON(req, res, next) : next())

/* implement shouldParseRequest (req) to return false for whatever you want to not parse json for */
```

Hope this helps!

**Comment by timaschew** [comment]
cool, thank you!
