### ISSUE TITLE
Logging/Timing?

### ISSUE THREAD

**Issue by niyazpk** [expressjs/body-parser#272]
I have an app where I am seeing occasional slow downs in request processing which I have narrowed down to the dispatch taking too much time. I am trying to figure out how much time the json parsing is taking for my request.

Is there a way to get this logged? Thanks!

"body-parser": "~1.17.1",

**Comment by dougwilson** [comment]
Hi @niyazpk that isn't a feature currently, though if you only have one request at a time, `DEBUG=body-parser:*` is close since the `debug` module will end each log line with the elapsed time since the previous log line, but since there is no debug log for "done!" you won't get the complete elapsed time from that (and it also won't work right if you have more than one request in parallel). Modules like `morgan` will output the total time the request / response spent in the server, but that doesn't provide a breakdown of each specific module.

The closest you can get right now is to simply wrap the middleware. Here is an example wrapper:
```js
function timeMiddleware(name, middleware) {
  return function (req, res, next) {
    var start = Date.now()
    middleware(req, res, function (err) {
      console.log('%s took %d ms', name, (Date.now() - start))
      next(err)
    })
  }
}
```

Then you wrap your module on use:
```js
app.use(timeMiddleware('json parser', bodyParser.json()))
```

Of course, since the body parser includes waiting for all the data from the network, large times you see here may be network times. You can use a packet capture to verify how long it took for the data packets for a request to actually arrive.

**Comment by HarshithaKP** [comment]
@niyazpk  Has the solution given helped in resolving your issue ??
