### ISSUE TITLE
Unsupported charset

### ISSUE THREAD

**Issue by dogenius01** [expressjs/body-parser#287]
When request sent without any header, bodyparser response this message.

{"status":415,"message":"unsupported charset \"X-WINDOWS-949\""}

and if bodyparser declared before helmet, it can be a security issue.

I tested this in REST client of webstorm.

**Comment by dougwilson** [comment]
I'm not sure what you mean by "without any header". There seems to be a Content-Type header with charset=X-WINDOWS-949 in your request which is why you're getting that response. Node.js does not have a way to decode X-WINDOWS-949 unfortunately.

If you believe this is in error, please provide all the following and I can reopen:

1. Version of this module
2. Version of Node.js
3. Complete server code that can reproduce the issue. Needs to be complete such that I can copy and paste without making alterations.
4. Instructions for exactly how to replicate issue.

Thanks!

**Comment by dogenius01** [comment]
If Node.js cannot decode X-WINDOWS-949, you can close this issue.

Thanks.
