### ISSUE TITLE
`deflate` encoded request results in `incorrect header check at Zlib.zlibOnError`

### ISSUE THREAD

**Issue by rjsteinert** [expressjs/body-parser#292]
Doing the [fetch seen here](https://github.com/rjsteinert/express-client-side-deflate-example/blob/master/public/index.html#L34) to [the route seen here](https://github.com/rjsteinert/express-client-side-deflate-example/blob/master/index.js#L17) results in the following error.

```
Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:142:17)
```

Am I doing something wrong? Perhaps the problem is with differences in how pako deflates and Zlib inflates?

**Comment by dougwilson** [comment]
Thanks for the reproduction case! I have never used `pako` before, but reading the docs and looking at a packet capture with Wireshark, my understanding is that the way you're using it is incorrect and you're corrupting the bytes being sent to the server. You need to remove the `{ to: 'string' }` in your code and then it works perfectly fine, because the bytes are correct over the wire now.

Here is a diff of the changes I made to your repo which make the button for automatic on sever work great:
```patch
diff --git a/public/index.html b/public/index.html
index ab85494..c4ba8b7 100644
--- a/public/index.html
+++ b/public/index.html
@@ -36,7 +36,7 @@
                         'Content-Encoding': 'deflate'
                     },
                     method: 'post',
-                    body: pako.deflate('hello world', { to: 'string' })
+                    body: pako.deflate('hello world')
                 })
             })
         </script>
```

**Comment by dougwilson** [comment]
I pasted the wrong diff there at first; I edited the post with the full diff (in case you're looking at an email notification).

**Comment by rjsteinert** [comment]
Yay it works! Thanks so much @dougwilson. Sending compressed data to Express using `body-parser` is quite easy :).

**Comment by rjsteinert** [comment]
I updated the example repo per your suggestion https://github.com/rjsteinert/express-client-side-deflate-example/commit/460f489d5438b11449f7d01cb9a0df796e2ad090

**Comment by vishnuSoftware** [comment]
Can any one help me out from below error in zlib

{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:154:17)
 errno: -5, code: 'Z_BUF_ERROR' }
