### ISSUE TITLE
using request object as stream

### ISSUE THREAD

**Issue by rajiff** [expressjs/body-parser#315]
How do we use request object as stream, if we use body-parser

because I have body-parser, though my client is streaming data to me, I am not able to process it like stream and I am getting `PayloadTooLargeError: request entity too large` error, I know how to overcome this (by changing the limit), but that will increase my memory usage, which is not acceptable

the only way around seems to be not using body-parser

I am really wondering, body-parser does not have a way to accept incoming data as stream?

**Comment by dougwilson** [comment]
This module does accept it as a stream, but the whole point of using this module is because you don't want to operate on a stream (which is the default without this module).

But if you want to just read as a stream, there is nothing this module actually gives you; by default req is a stream of the body and you can read it as such.

**Comment by dougwilson** [comment]
Basically req is already a stream you can read. The body-parser module takes that and provides a non-stream interface for folks who don't want to bother with streams. If you want to read as stream, no purpose to use this module,  as it is the opposite of what you want to do :+1:
