### ISSUE TITLE
Express body parser not considering + as data when passing + in query.

### ISSUE THREAD

**Issue by Raju-t** [expressjs/body-parser#316]
When passing data in get request as query in url. Express does not picks + symbol 
Like I pass email=rajuthapa+232@zapbuild.com in query it doesn't recognize + and when I access req.query.email it shows "rajuthapa 232@zapbuild.com"

I have used:
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true, limit: '200mb' }));

**Comment by blakeembrey** [comment]
Quick couple of notes:

* `req.query` is for query strings, it's not related to body parsing
* Query strings need to be URL encoded - in your example you are using `+` directly which is invalid because in URL encoding, a `+` means a space (hence, you get a space instead of the plus)

This isn't an issue with the server, it's an issue with your client. Make sure you do proper encoding of anything you send. With query string parameters, you can use `encodeURIComponent()`. For example (notice the output is encoded):

```js
encodeURIComponent('rajuthapa+232@zapbuild.com') //=> "rajuthapa%2B232%40zapbuild.com"
```

**Comment by blakeembrey** [comment]
There's some more information about query strings on Wikipedia: https://en.wikipedia.org/wiki/Query_string. See specifically the section on "URL Encoding".
