### ISSUE TITLE
How to use bodyParser.json with multiple middlewares ?

### ISSUE THREAD

**Issue by Neustart** [expressjs/body-parser#332]
Hi there!
I have a [question here](https://stackoverflow.com/questions/52045951/how-to-use-multiple-global-middlewares-in-node-js-using-typescript) with more details. 
I am not able to declare my own middleware and using it with this one:
```
bodyParser.json({
          type: "*/*"
})
```

If I declare a few `app.use(...)`- no one won't works. Once I remove bodyParser.json all works well. 
How can I add this middleware to my express app to leave all other still working?

**Comment by dougwilson** [comment]
So I read this and your SO question, but I don't understand what you're asking,  I'm sorry.

**Comment by Neustart** [comment]
@dougwilson I have my node js application and I need to do two things:
1) I want to write my own middleware for token validation for each reqeust
2) I want to allow only json body type for input request
I need those both things works at the same time. 
So, I've wrote my own middleware for token validation:
```
let tokenFilter = async function filtering(req, res, next) {
    //logic
};
```

Then I registering this middleware using the next code:
`app.use(tokenFilter);`

This allows me to check each request and do some logic with token validation. 

At the same time, I want to use your middleware, to allow only json body type. I mean this one:
```
bodyParser.json({
          type: "*/*"
})
```

Before I have my own middleware for token validation your middleware I was registering using this code:
```
app.use(bodyParser.json({
          type: "*/*"
}));
```

Once I added my middleware for token validation they are both (your and mine) stop works. 
So I am looking for a way how to register both of them at the same time.

**Comment by dougwilson** [comment]
I see. I still don't quite understand but maybe if you can provide all the following I can get it:

1. Version of node.js this module and any other you are using.
2. Complete code that I can copy and paste and run without any modification to see the issue.
3. Complete instructions on how to run the above code and exactly how to replicate the issue.
4. A description of what you expect the outcome to be in contract to what actually happens when I follow you above steps.

Thanks!

**Comment by dougwilson** [comment]
Closing due to no response.
