### ISSUE TITLE
[bug] `body` property in request body is not allowed

### ISSUE THREAD

**Issue by leejh3224** [expressjs/body-parser#333]
When my request body includes `body` field, it emits these error below.

```
SyntaxError: Unexpected token 피 in JSON at position 0
```

```
"error": {
             "expose": true,
              "statusCode": 400,
              "status": 400,
              "body": "피타고라스 정리!",
              "type": "entity.parse.failed"
}
```

But if I change the name of the field into something else, error goes away.

I think this behavior is not intended thus it must be bug.

**Comment by dougwilson** [comment]
I'm not able to reproduce the error.

**Comment by dougwilson** [comment]
Please either provide a pull request with a fix, or all the following information:

1. Version of node.js this module and any other you are using.
2. Complete code that I can copy and paste and run without any modification to see the issue.
3. Complete instructions on how to run the above code and exactly how to replicate the issue.
4. A description of what you expect the outcome to be in contract to what actually happens when I follow you above steps.

Thank you.

**Comment by leejh3224** [comment]
Oh, I found out what was wrong in my code.

```
export const savePost = async ({ body }, res, next) => {
  const { error } = Joi.validate(body, savePostSchema)

  if (error) {
    return res.status(400).json({ error })
  }

  const {
    title,
    originalTitle,
    channelUrl,
    channelName,
    videoId,
    body, // name collision here
    thumbnail,
    category,
    level,
  } = body

  try {
    const [videoOwner] = await VideoOwner.findOrCreate({
      where: {
        channel_url: channelUrl,
        channel_name: channelName,
      },
    })

    const postPayload = {
      title,
      original_title: originalTitle,
      video_owner_id: videoOwner.toJSON().id,
      video_id: videoId,
      body: postBody,
      thumbnail,
      category,
      level,
    }

    await Post.build(postPayload)
      .save()
      .toJSON()

    return res.json({ success: true })
  } catch (error) {
    next(error)
  }
}
```

I accidentally used same name for destructured `req.body`.

I think this caused the issue.

As this is not a bug, I'm closing the issue.
