### ISSUE TITLE
very very weird behaviour with non latin characters on req.body 

### ISSUE THREAD

**Issue by cAstraea** [expressjs/body-parser#334]
Using exactly the same node version v10.12 , same code base. On my local machine this parses correctly
  firstname: 'ラズバン',
on the server 
 firstname: '??

and hangs 

Why is this happening ? I'm using body parser like so 

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }))

**Comment by dougwilson** [comment]
Very strange.  Can you help us reproduce the issue? You can always provide a pull request with a fix, or all the following information:

1. Version of node.js this module and any other you are using.
2. Complete code that I can copy and paste and run without any modification to see the issue.
3. Complete instructions on how to run the above code and exactly how to replicate the issue.
4. A description of what you expect the outcome to be in contract to what actually happens when I follow you above steps.

Thank you.

**Comment by dougwilson** [comment]
Closing due to no response.
