### ISSUE TITLE
Invalid JSON response

### ISSUE THREAD

**Issue by RORVI** [expressjs/body-parser#339]
Hello !
I am facing an issue with an application written in ExpressJs. I have a PUT endpoint used for updating an object in MongoDB. The update is successfull, but randomly, the endpoint returns a truncated JSON.It is missing the last "}" character in the JSON response body and the consumer application is crashing while trying to deserialize the response JSON. I've investigated and found that the content length in the response header does not match the actual length of the body.
Content-length is returning a value which indicates that it should have 3 more elements in the response body. I am currently running under a Windows 10 environment.
I am not 100% sure but i think these 3 missing characters are the following: "}\r\n".
I am using Express version 4.14.0 with MongoDB version 3.4 and body-parser 1.15.2.

**Comment by dougwilson** [comment]
Hi! Thanks for the report! This module is really only used in parsing the incoming body of a request and should have nothing to do with actually writing a response out. I can take a look, but from your description I have no idea how this module could result in what you're describing. Can you elaborate on that point?

**Comment by RORVI** [comment]
The reported Content-Length is 6597 and the actual length of the invalid JSON response is 6594.
I am building the response like this:

return res.status(200).json({
    success: true,
    error: null,
    data: userData
});

Where could this come from ?

**Comment by dougwilson** [comment]
All this module does is stated in the readme. It does not provide an api res.staus and stuff. Does the issue still occur if you remove this module from the app?

**Comment by RORVI** [comment]
I'n not trying to pin this on a module. I am simply trying to figure this out, as i cannot find similar issues anywhere else. This quite confusing for me, as I am not encountering this sort of issue anywhere else in the codebase, but only on 3 specific endpoints, which have a very erratic behavior with regards to this issue. However, I am using the same approach for building responses, which should ensure that this kind of response issue would appear everywhere.
I think this might be an ExpressJS issue, but am not sure.

**Comment by RORVI** [comment]
I'm thinking that maybe you have some sort of a buffer mechanism in the background with some restrictions on it ?
I am not sure though.

**Comment by dougwilson** [comment]
Gotcha. So if it's not an issue with this module, this may be the wrong forum to make the report. Ideally the issue is opened in the module with the issue. The only code provided so far has nothing to do with this module, and your description doesn't sound like something that this module would cause, so no idea how a fix in this module would help your situation is all.

To help figure out the cause, one method is through the process of elimination. That's why I was just asking if you removed this module from the code and see if it still happens. That would at least start to determine the direction to go as to what may be causing the issue.

If you have another method to figure this out, I'm all ears, just let me know what the next step you would like to try if you don't want to try the step of removing this module from the code and seeing if the issues goes away or not.

**Comment by RORVI** [comment]
If i remove the body-parser, i can really make requests to my application anymore.
If i was to remove the module which serializes the response, it would mean removing Express altogether. 
I was just looking through the source code in Express, and i found something that might impact this, in the response.js file, on line 942 :   this.set('Content-Length', Buffer.byteLength(body));
Could this have an impact regarding my issue ?

**Comment by dougwilson** [comment]
It's possible. If you put a debugger break point at that spot, does the value it sets in the header match the `body` variable length? And does the `body` variable's contents have the end of the response missing or intact?

**Comment by RORVI** [comment]
I can't really say for sure. My application is deployed to production and users have been reporting this constantly. 
However, me and my team have only been able to reproduce it 2 times in 2 and a half weeks of debugging and investigations. It is very erratic and extremely hard to reproduce.
The application which consumes the endpoint crashes because of the invalid JSON in the response. It is an iOS app, and the parsers crash. The response is missing the closing bracket at the end of the JSON "}".
We have loggers on both the mobile app and the backend. The mobile app retrieved the content length 6597, and the invalid JSON had a length of 6596 bytes.

**Comment by dougwilson** [comment]
Yes, very strange. All I can really say right now is that I (at least me) have never heard of this issue before. I have no idea what would just cut off the end like that in this module or express itself.

If the issue cannot be reproduced under a debugger, what would be another course of action to determine the cause?

**Comment by dougwilson** [comment]
That method (res.end) is part of Node.js core and would be a question better suited for Node.js. I don't know what the answer is on that one off hand.

**Comment by dougwilson** [comment]
Anyway, if you think the issue is in express, I would say let's move the issue over there, especially since there are a lot more folks active there who can help with express issues than on this module repo. If there is evidence that the issue is specifically this module, I can reopen the issue in this repo, of course, but it seems you're looking at code not part of this module as the possible source.
