### ISSUE TITLE
Bodyparser returns  undefined value JSON

### ISSUE THREAD

**Issue by aviralgoyal** [expressjs/body-parser#340]
I've copied the JSON code in the documentation and sent a post request using Postman. I get a return value "undefined". I am attaching the code below, please advice. Thanks in advance.

**Node Code:**

// bodies of all incoming requests. This is the simplest setup.

var express = require('express')
var bodyParser = require('body-parser')

var app = express()
const port = 3000
 
// create application/x-www-form-urlencoded parser
var urlencodedParser = bodyParser.urlencoded({ extended: false })
 
// POST /login gets urlencoded bodies
app.post('/login', urlencodedParser, function (req, res) {
  if (!req.body) return res.sendStatus(400)
  res.send('welcome, ' + req.body.username)
})
 
app.listen(port, () => {
  console.log('Server started at port: ' + port)
})

**POSTMAN Request code**

POST /login HTTP/1.1
Host: localhost:3000
Content-Type: application/json
cache-control: no-cache
Postman-Token: 98d3bcb2-1326-4358-8d2a-91b25fbfae89
{
    "username": "aviral"
}------WebKitFormBoundary7MA4YWxkTrZu0gW--

**Response:**

welcome, undefined

**Comment by dougwilson** [comment]
Your request has the content type of application/json but your code has a urlencoded parser, not a json parser.

**Comment by dougwilson** [comment]
Hi! It's no problem. Our only documentation is our README, which seems pretty straightforward, at least to me.

It starts out with the following:

> All middlewares will populate the req.body property with the parsed body when the Content-Type request header matches the type option, or an empty object ({}) if there was no body to parse, the Content-Type was not matched, or an error occurred.

Since the example you pasted has "Content-Type: application/json" it says that only a parser with "type" set to "Content-Type: application/json" will parse your example request.

You could read through each parser, or even just ctrl+f for Content-Type: application/json which will bring up the section for bodyParser.json https://github.com/expressjs/body-parser/blob/master/README.md#bodyparserjsonoptions which is the first one documented since most people want that one.

If you have any specific tips on changes we can make to our readme to help, we would love to hear them and improve!
