### ISSUE TITLE
Content-Length and body length mismatch causes the application to hang.

### ISSUE THREAD

**Issue by chainhead** [expressjs/body-parser#373]
I submitted a `GET` request with a body that is _much_ smaller than the `Content-Length` header value, e.g. `200`. I never get a response back.

Can you please let me know what is missing?

**Comment by dougwilson** [comment]
The module will wait until your defined request timeout to get the full body. Since `Content-Length` defines the length of the body component in the HTTP framing, sending less bytes than that value there is no end of transmission marker, so for all this module knows the client is working to send the rest of the bytes, so waits for them.

You can change the timeout length from the default Node.js of 2 minutes.
Server-wide default timeout: https://nodejs.org/dist/latest-v10.x/docs/api/http.html#http_server_settimeout_msecs_callback
Per-request timeout: https://nodejs.org/dist/latest-v10.x/docs/api/http.html#http_message_settimeout_msecs_callback

**Comment by janacm** [comment]
For any passerbys from NextJS receiving a similar error, try switching from fetch to axios.

For a full solution, see here: https://janac.medium.com/nextjs-fails-with-und-err-req-content-length-mismatch-after-redirect-from-server-0acdc0bfb194
