### ISSUE TITLE
Content type not defined in req.headers(not a real issue)

### ISSUE THREAD

**Issue by PabloWong** [expressjs/body-parser#380]
sometime content type is not defined in req.headers but you know the body will be a json. 
app.use(bodyParser.json({type: function(){return true;}}));
will solve the problem, it was hard for me to find this solution, so please make it more clear in the doc

**Comment by dougwilson** [comment]
Hi @PabloWong sorry you're having trouble. IMO the docs are already clear. For example, the first sentence in the bodyParser.json docs is "Returns middleware that only parses json and only looks at requests where the Content-Type header matches the type option."

If you think it can be made clearer, please let me know how the wording should be changed in order to help. We come from different background, so what is clear to each of us differs :) But by you saying it's not clear doesn't help me understand _how_ I can make it clearer.

**Comment by PabloWong** [comment]
wow what a fast reply, 
I hope docs should say which are defaults, and how to bypass the content-type check in cases where req.headers['content-type'] is undefined. how to match undefined content type? Was very confusing to me that raw was looking for a default content-type too, as raw in my mind means raw data and not application/octet-stream. As I say in the issue title thats not a real issue as most of the time content-type is specified, but leaving this issue, will come out in google search and sometimes can help. 
I hope this issue can be closed.
thanks for your fast reply.

**Comment by dougwilson** [comment]
> From doc I can think that writing bodyParser.json({type:null}) can help but no, if type is null or false it go looking for default.

Why would you think that? The doc outlines exactly what type can be:

> The type option is used to determine what media type the middleware will parse. This option can be a string, array of strings, or a function.

What would make it sound like "null" or "false" would be a value value? Neither of those, to me, are a string, an array of strings, or a function.

**Comment by PabloWong** [comment]
you are right, I was blinded.
