### ISSUE TITLE
 can’t get request.body  when content-type = ‘‘

### ISSUE THREAD

**Issue by xiaohao0416** [expressjs/body-parser#386]

**Comment by jonchurch** [comment]
If the content type is empty, we can't infer how to parse the body. In that case `req.body` will be set to an empty object. 

Is `req.body` undefined? 

If you can post a minimal example reproducing the issue, I can take a closer look.

But it is expected behavior for `req.body` to be empty if your request is sent with an empty content type.

**Comment by wesleytodd** [comment]
If you come back and provide more information, please feel free to re-open this @xiaohao0416

**Comment by moiz-frost** [comment]
Hi, I'm facing a similar issue. Problem is that the third party application doesn't send the `content-type` header but it does contain a request body. In that case req.body is set to an empty object. Is there a way to let the programmer manually handle such cases?

**Comment by dougwilson** [comment]
The type option accepts a function in which you can implement any logic you want to determine if the request body should be parsed.
