### ISSUE TITLE
PayloadTooLargeError: request entity too large 

### ISSUE THREAD

**Issue by fatemehmemat** [expressjs/body-parser#400]
hi
I get this error when sending large photos :
PayloadTooLargeError: request entity too large
i use this code but didnt work:
app.use(bodyParser.json({ limit: '50mb' }));
app.use(bodyParser.urlencoded({ limit: '50mb', extended: true, parameterLimit:50000}));

when  in nodeModule/body-parser/lib/types/json
i change this code 
 var limit = typeof opts.limit !== 'number'
    ? bytes.parse(opts.limit || '100kb')
    : opts.limit

to 
 var limit = typeof opts.limit !== 'number'
    ? bytes.parse(opts.limit || '100mb')
    : opts.limit

everythings ok but when npm i everything goes back to the previous state
Thank you for your help

**Comment by mastermatt** [comment]
@fatemehmemat what is the content type of the request that includes the photos? I assume it's `multipart/form-data` instead of `application/json` or `application/x-www-form-urlencoded`.

You might want to look into using the [`.raw` method](https://github.com/expressjs/body-parser#bodyparserrawoptions), or even using [Multer](https://github.com/expressjs/multer) instead for your upload routes.

**Comment by davidmashe** [comment]
no response to question, closing issue. Can re-open if more activity occurs.

**Comment by sstamoulas** [comment]
I ran into the same issue. PayloadTooLargeError: request entity too large. For anything above 10MB. Because I am working with `firebase functions` I must use `busboy`. `Multer` is not recommended to use with `firebase functions`.

    app.use(bodyParser.json({ limit: '1gb' }));
    app.use(bodyParser.raw({ limit: '1gb' })); 
    app.use(bodyParser.urlencoded({
      limit: '1gb',
      extended: true,
    }));
