### ISSUE TITLE
BadRequestError: request aborted

### ISSUE THREAD

**Issue by dannysmc95** [expressjs/body-parser#419]
Hello!

I have seen a few issues that have been opened and locked based on the above error.
I am willing to work through it and find out where it is failing or what I am doing that is causing it.

So I have a project, which is based on my own personal framework, the framework is what utilises express and the body-parser package, and then the application in question is built on top.

The error is below:
```
BadRequestError: request aborted
    at IncomingMessage.onAborted (/home/containers/everstar-web/app/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:315:20)
    at abortIncoming (_http_server.js:561:9)
    at socketOnClose (_http_server.js:554:3)
    at Socket.emit (events.js:327:22)
    at TCP.<anonymous> (net.js:673:12)
```

It seems to occur when there is actually no request being called, I see it popup in logs while I am developing, so I am not 100% what causes it to show, but it shows on any page, but doesn't seem to be linked the original GET request for the page.

The project I am working on is a simple website, which I do not wish to just share on here, so if you let me know if you can help, then I can add you to the project (it's in Github) and you can access/pull it down and try it out.

The framework underneath is here: [https://github.com/dannysmc95/rewyre/](https://github.com/dannysmc95/rewyre/).

If you have any ideas I am all ears, just let me know who to add to the project.
To note it's not the end-all of things, but it is quite annoying that it comes up in the logs.

Thanks in advance.

**Comment by robsonkades** [comment]
I have the same problem when a GET request is made by passing a json in the body
This error is presented in the error middleware in the express, but as the `BadRequestError` class is not being exported, I am not able to correct it.

`app:info:app:warn:app:debug:app:error BadRequestError: request size did not match content length
  app:info:app:warn:app:debug:app:error     at IncomingMessage.onEnd (/Users/robsonkades/git/serverless-typescript/node_modules/raw-body/index.js:263:12)`

**Comment by angeloff** [comment]
Hello,

I'd like to join this thread and not open a new one.
I am experiencing the very same problem.

My team has been involved in upgrading a legacy nodejs (6.12.0) project which had body-parser version 1.4.3.
Now with node itself upgraded to 12.18.3, the body-parser that comes with express is version 1.19.0.
We've started experiencing the request aborted problem which is mentioned in several issues here in this repository.

It seems that this change comes with v 1.12.3: https://github.com/expressjs/body-parser/issues/93
As far as I understand, previously some requests would hang and a fix was introduced which produces this error.

We've enhanced our error logging and it shows that such requests have _content-length_ header set to something different than 0. The _request.aborted_ error produced has the expected property set to the same value as the header.
But the _received_ property value is 0 and the request body is an empty object.

My question is, what would you recommend as a solution?
Do we need to handle such errors and ignore them since the client has aborted the request and there is nothing really that could be done? How can we validate the hanging issue in the earlier versions?
Can you suggest a simple middle-ware that might be used with the old code to actually show that this was happening before as well? This way, we can be sure that this was a previously masked defect that is now visible and could be safely ignored.

Thank you!

**Comment by dougwilson** [comment]
Hello, and apologies for the confusion around this error. This error is emitted _when Node.js HTTP server states the request is aborted_. This module simply forwards the error to your error logic; this module itself does not cause or contain logic around when a request is determined aborted. Node.js also is responsible to providing the data to this module to consume, through the `data` events on the request. If you are getting the forwarded error where the `received` property is 0, it indicates that Node.js did not provide any `data` events for the request before Node.js indicated the request was aborted.

> My question is, what would you recommend as a solution?

There is no solution within this module; if a request is aborted, then the best this module can do is raise the error.

> Do we need to handle such errors and ignore them since the client has aborted the request and there is nothing really that could be done? How can we validate the hanging issue in the earlier versions?

What to do with the errors is up to your specific application needs. To validate the handing issue in earlier versions, you can log when any request comes in and log again when you respond to a request. You will notice a hang when you log your application get a request, but no response was ever generated. There are many ways you can do this, depending on your specific application, but a very basic wrapper can achieve this as well:
```js
const _json = bodyParser.json()
app.use((req, res, next) => {
  const id  = `${Date.now() + Math.random()}`
  console.log('Start #%s', id)
  _json(req, res, (err) => {
    console.log('End $%s', id)
    next(err)
  })
})
```

**Comment by angeloff** [comment]
Thank you for coming back to this and the provided details. We did something similar some time ago to validate the case and it proved to be this way. In the end, we started ignoring the aborted requests. It was a heavy upgrade due to the big gap of versions we needed to catch up with but lesson hopefully learnt now. :)
