### ISSUE TITLE
There seems to be no support for the PATCH method.

### ISSUE THREAD

**Issue by djalbat** [expressjs/body-parser#426]
GET, PUT, POST and DELETE all work fine but the `body` object is empty for PATCH methods. Is this be design?

```
const express = require("express"),
      bodyParser = require("body-parser"),
      CookieParser = require("cookie-parser");

const cookieParser = CookieParser(),
      jsonBodyParser = bodyParser.json(),
      restrictedRouter = express.Router();

restrictedRouter.use(cookieParser);

restrictedRouter.use(jsonBodyParser);

restrictedRouter.patch(THEME_API_PATH, themePostAPIHandler);

...
```

The handler gets called here with either `.post(...)` or `.patch(...)` but in the latter case, no parsing of the JSON body seems to take place.

```
  "dependencies": {
    "body-parser": "^1.19.0",
    "cookie-parser": "^1.4.5",
    "express": "^4.11.2"
  },
```

Many thanks in advance.

**Comment by dougwilson** [comment]
Hi @djalbat this module does not do any validation/checking of the HTTP method; all HTTP methods work with this module just fine. I have taken what you have posted above and turned it into a code-complete example and it works without issue. This means that the issue you are having is likely caused by some detail you may have left out in your post on accident. Unfortunately that issue would lie outside this module since it does function with PATCH as demonstrated here:
```
$ cat app.js
const express = require("express"),
      bodyParser = require("body-parser"),
      CookieParser = require("cookie-parser");

const cookieParser = CookieParser(),
      jsonBodyParser = bodyParser.json(),
      restrictedRouter = express.Router();

restrictedRouter.use(cookieParser);

restrictedRouter.use(jsonBodyParser);

restrictedRouter.patch('/theme/api/path', (req, res) => {
    res.send(`Ahoy! Your body ${JSON.stringify(req.body)} was recieved!`);
});

express().use(restrictedRouter).listen(3000);

$ npm i express body-parser cookie-parser
+ cookie-parser@1.4.5
+ body-parser@1.19.0
+ express@4.17.1
added 51 packages from 37 contributors and audited 51 packages in 3.211s
found 0 vulnerabilities

$ node app &
[1] 1345

$ curl -XPATCH -H'Content-Type: application/json' -d'{"foo":"bar"}' http://localhost:3000/theme/api/path
Ahoy! Your body {"foo":"bar"} was recieved!
```

**Comment by djalbat** [comment]
Hello Doug,

that's fine. I'd assumed what you say, in fact, namely that the module has no idea about the HTTP method, so was surprised when things didn't work for me. I will have to look into the problem in more detail.

Thank you very much for the prompt response.

Kind regards,\
James

**Comment by briangleeson** [comment]
I stumbled in here looking for an answer as I had a similar problem with PATCH requests. In case anyone else runs into a similar issue, the fix was as follows. For my case the body was being left out as I was using `application/merge-patch+json` as the content-type on patch requests, with bodyParser.json only accepting `application/json` content by default. Adding `type: [ "application/json", "application/merge-patch+json"]` to the options in bodyParser.json solved the problem for me
