### ISSUE TITLE
urlencoded parser prevents some GET request from getting to the right router

### ISSUE THREAD

**Issue by yuxiaolejs** [expressjs/body-parser#447]
Recently I am trying to set up a gateway authenication server based on the auth_request module of nginx and express as a backend.
I found nginx will return 504 if I add the urlencoded to my express back end, and I figured this problem out by disabling one middleware at a time and the problem appears to be linked with express.urlencoded.
I have to use the urlencoded middleware for processing other requests, so I have to stick with it.
I will provide more infomation later because I have to go to my class.

**Comment by dougwilson** [comment]
Hi, thanks for your issue. Unfortunately there isn't enougj information to look into what is causing it. When you are able, please include a reproduction case and instructions.

**Comment by yuxiaolejs** [comment]
Steps to reproduce:
1. Set up nginx reverse proxy with auth_request (like the config in the previous post)
2. Set up nodejs program that returns 200 code for all requests(refer to the picture above)
3. Send a post query to the nginx reverse proxy
4. The node program should NOT receive the post query if urlencoded is enabled

**Comment by yuxiaolejs** [comment]
The data is gitlab login credentials, I can grab the detail of it later

**Comment by dougwilson** [comment]
Yes, I tested with nginx and it is an issue with your nginx config. Using the example auth request config in their documentation works fine: http://nginx.org/en/docs/http/ngx_http_auth_request_module.html#example

The issue is you have configured nginx to forward to node.js server a content-length header but no body, so thia module will wait for the body until timeout. Their example will have it not pass the body along to your auth.
