### ISSUE TITLE
JSON.parse error should not propagate down the middleware chain

### ISSUE THREAD

**Issue by nounder** [expressjs/body-parser#567]
Middleware throws unexpectedly (returning 500 response) for requests with JSON payload (including `Content-Type`) header. I think that `400 Bad Request` should be returned instead.

## Example

For following request:

```
curl -X POST 'http://localhost:3010' -H "Content-type: application/json"  --data 'INCORRECT'
```

The middleware unexpectedly fails during `JSON.parse` call and returns 500 instead of 400:

```
SyntaxError: Unexpected token 'I', "INVALID_JSON" is not valid JSON
    at JSON.parse (<anonymous>)
```

## Repro

```js
const express = require('express');
const bodyParser = require('body-parser');

const app = express();
const port = 3010;

app.use(express.static('static'));
app.use(bodyParser.json());

app.all('/', (req, res) => {
  console.log(req.body);

  res.end('ok');
});

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`);
});
```

Live example: https://stackblitz.com/edit/stackblitz-starters-buazybtv?file=index.js

**Comment by nounder** [comment]
Okay, this is embarrassing. Bug happened because our middleware responsible for global error handling overwrote status code.

**Comment by bjohansebas** [comment]
That would be the expected behavior, events with 5xx codes are server-side errors. `JSON.parse` can handle various JavaScript typos, check the documentation on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse). The input you are providing is incorrect.  

The curl command should look something like this:

```console
curl -X POST 'http://localhost:3010' -H "Content-type: application/json"  --data '"INCORRECT"'
```

**Comment by kyle-pena-nlp** [comment]
I respectfully disagree.  This error is indeed generated on the server (because where else would it be generated if we're using bodyparser?), but that doesn't mean that the error is *semantically* a 500.  400 means "Bad Request".  If we look at MDN - which I think is fairly authoritative - the *first example* of a bad request is invalid JSON syntax.  https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

**Comment by wesleytodd** [comment]
If you would like to properly handle this error you can in your application code. There are [a few docs to help](https://github.com/expressjs/body-parser?tab=readme-ov-file#errors) (although reading them now in this context I think we can improve them quite a bit to show best practices for this common type of error handling.
