### ISSUE TITLE
Raw parser for empty bodies

### ISSUE THREAD

**Issue by boo1ean** [expressjs/body-parser#89]
Currently there is a types inconsistency in `bodyParser.raw()`.

If we have non-empty body -> `Buffer`
If we have empty body -> `Object`

https://github.com/expressjs/body-parser/blob/master/lib/types/raw.js#L58-L63

What do you think about returning empty buffer for empty request bodies?

Thanks.

**Comment by dougwilson** [comment]
There is a 2.x branch that represents the next major release. It has a similar change already. Let me know if that works for you :)

**Comment by dougwilson** [comment]
Closing since I didn't hear anything back and there is already a change in the pending 2.0 branch.

**Comment by xaka** [comment]
I'm glad I've found this one otherwise GitHub would suffer from another wasted ID and go down. It would be really nice to have consistency for `raw` parser. Empty buffer sounds like perfect and only solution here. Would it be possible to make it happen for 1.x as it doesn't seem like 2.x is moving anywhere?

**Comment by dougwilson** [comment]
Hi @xaka, this module is currently under proposal to move under the Node.js foundation to get it moving on it's feet again. Releasing the change under 1.x would break people's existing code, especially because `npm` default to using the `^` modifier. The changes really do need to be in a 2.x release, I'm sorry.

You can always depend on the GitHub branch in your `package.json` in the meantime, if that is feasible.
