### ISSUE TITLE
bodyParser.text() returns undefined, but bodyParser.json()

### ISSUE THREAD

**Issue by dmathieu** [expressjs/body-parser#92]
On all requests, we're seeing a weird behavior where `#text()` returns undefined, but `#json()` works.

**Comment by dougwilson** [comment]
What is the `Content-Type` header for those requests?

**Comment by dougwilson** [comment]
The reason I ask is because by default (see docs at https://github.com/expressjs/body-parser#type-2), `bodyParser.text()` ignores any request that doesn't have the Content-Type set to `text/plain` unless you change it. If json is working but not text, that sounds like to me all those headers are set to `application/json` and if you want the text parser to try and parse them, you'll need to do:
```js
bodyParser.text({ type: 'json' })
```

Another important note is that in Node.js you can only read the stream once, so you cannot use two parsers to parse the exact same request (the first matching parser will always be the one that will parse).

**Comment by jmonster** [comment]
thanks @dougwilson !

**Comment by dougwilson** [comment]
@jmonster @dmathieu let me know if you guys have any questions; we're part of the same parent company ;)

**Comment by dmathieu** [comment]
Thanks @dougwilson :)
