### ISSUE TITLE
.json not accepting json-patch+json

### ISSUE THREAD

**Issue by LinusU** [expressjs/body-parser#96]
If the content-type is set to `application/json-patch+json` the default `bodyParser.json()` parser will not consider that body to be of json type. I think that it should.

**Comment by dougwilson** [comment]
That's not the same type. Just use the `type` option to change it to whatever you want to accept.

**Comment by dougwilson** [comment]
```js
app.use(bodyParser.json({ type: 'application/json-patch+json' }))
```

**Comment by LinusU** [comment]
Thanks for quick reply! Yes I understand that they are not the same type but I was thinking that the bodyParser.json is for "json encoded content" which I guess that every "+json" content type is.

Anyhow, it's entirely up to you. For reference, this is what I'm using currently:

```javascript
bodyParser.json({ type: ['json', '+json'] })
```

**Comment by dougwilson** [comment]
Gotcha. But yes, the default is to _not be surprising_ and restrictive. Just think about if you just used `bodyParser.json()` in your API and then later you migrated to a new stack in a new language and broke customers because they happened to be sending with `application/gibberish+json` and it just happened to work in your Node.js stack. Basically, you should opt-in to very wide APIs and we want the default to be some-what sane :)

FWIW, the old JSON parser that was part of `connect` did what you're asking and there were a lot of complaints, which is partially what has driven the conservative default: massive community feedback from unintentional API breakages.

**Comment by LinusU** [comment]
Ahh, that makes sense! Actually when I think about it, the way I have implemented it now isn't ideal since it will accept both json and json-patch for every endpoint. What I really want is some endpoints with json and some with json-patch.

Conservative defaults sounds really sensible, I'm all for it!
